name: syncfusion_pdfviewer_web
description: Web platform implementation of the Flutter PDF Viewer library that lets you view the PDF documents seamlessly and efficiently.
version: 21.2.5
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_pdfviewer_web

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.7.1
  meta: ^1.3.0
  syncfusion_pdfviewer_platform_interface:
    git:
      url: https://SyncfusionBuild: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@github.com/essential-studio/flutter-pdfviewer-platform-interface
      path: flutter_pdfviewer_platform_interface/syncfusion_flutter_pdfviewer_platform_interface
      branch: release/25.1.1
      ref: release/25.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
     web:
        pluginClass: SyncfusionFlutterPdfViewerPlugin
        fileName: pdfviewer_web.dart
