name: Report a bug
description: |
  You have discovered a bug in our widgets that is causing your application to crash 
  or throw an exception. It appears that a widget is buggy, or something is not functioning correctly.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using Syncfusion widgets!

        If you are looking for support, please check out our documentation, knowledge base, 
        and feedbacks. If you are unable to find a solution, please report the bug here.

          - [User Guide Documentation](https://help.syncfusion.com/flutter/introduction/overview)
          - [Knowledge Base](https://support.syncfusion.com/kb/cross-platforms/category/79)
          - [Feedbacks](https://stackoverflow.com/questions/tagged/flutter?sort=frequent)
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Kindly provide us with detailed steps to replicate the issue you are experiencing.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Code sample
      description: |
        Kindly create a simplified, reproducible example that demonstrates the issue 
        and include it within the code block delineated by backticks.
        Note: Refrain from posting screenshots containing code.
      value: |
        <details open><summary>Code sample</summary>

        ```dart
        [Paste your code here]
        ```

        </details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots or Video
      description: |
        Upload any screenshots or video of the bug if applicable.
      value: |
        <details open>
        <summary>Screenshots / Video demonstration</summary>

        [Upload media here]

        </details>
  - type: textarea
    attributes:
      label: Stack Traces
      description: |
        If it is a runtime exception, kindly provide the stack trace from the console.
        If the traces are too large to be uploaded to GitHub, you may upload them as a `zip` file.
      value: |
        <details open><summary>Stack Traces</summary>

        ```json
        [Paste the Stack Traces here]
        ```

        </details>
  - type: dropdown
    id: target_platforms
    attributes:
      label: On which target platforms have you observed this bug?
      multiple: true
      options:
        - Android
        - iOS
        - Web
        - Web (Android browser)
        - Web (iOS browser)
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - type: textarea
    attributes:
      label: Flutter Doctor output
      description: |
        Kindly share the complete details generated by executing the command 
        `flutter doctor -v` in your terminal.
      value: |
        <details open><summary>Doctor output</summary>

        ```console
        [Paste your output here]
        ```

        </details>
    validations:
      required: true