name: officecore_example
description: Demo for creating a Excel file using syncfusion_flutter_officecore package.

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
  open_file: ^3.0.1
  syncfusion_flutter_xlsio:
     git:
      url: https://SyncfusionBuild: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@github.com/essential-studio/flutter-xlsio
      path: flutter_xlsio/syncfusion_flutter_xlsio
      branch: development
      ref: development


# The following section is specific to Flutter. 
flutter:
  uses-material-design: true
