name: syncfusion_flutter_sliders
description: A Flutter Sliders library for creating highly customizable and UI-rich slider, range slider, and range selector widgets for filtering purposes.
version: 24.2.9
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_sliders

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: '>=0.18.1 <0.20.0'

  syncfusion_flutter_core:
    git:
      url: https://SyncfusionBuild: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@github.com/essential-studio/flutter-core
      path: syncfusion_flutter_core
      branch: release/25.1.1
      ref: release/25.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
