name: syncfusion_flutter_datagrid_export
description: The Syncfusion Flutter DataGrid Export library is used to export the DataGrid content to Excel and Pdf format with several customization options.
version: 24.2.9
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_datagrid_export

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  syncfusion_flutter_datagrid:
    git:
      url: https://SyncfusionBuild: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@github.com/essential-studio/flutter-datagrid
      path: flutter_datagrid/syncfusion_flutter_datagrid
      branch: release/25.1.1
      ref: release/25.1.1
  
  syncfusion_flutter_xlsio:
    git:
      url: https://SyncfusionBuild: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@github.com/essential-studio/flutter-xlsio
      path: flutter_xlsio/syncfusion_flutter_xlsio
      branch: release/25.1.1
      ref: release/25.1.1
  
  syncfusion_flutter_pdf:
    git:
      url: https://SyncfusionBuild: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@github.com/essential-studio/flutter-pdf
      path: flutter_pdf/syncfusion_flutter_pdf
      branch: release/25.1.1
      ref: release/25.1.1

  collection: ">=1.9.0 <=2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
